// Each new term in the Fibonacci sequence is generated by adding the previous two terms.
// By starting with 1 and 2, the first 10 terms will be:

// 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
// By considering the terms in the Fibonacci sequence whose values do not exceed n, 
//find the sum of the even-valued terms.

function fiboEvenSum(n) {
    let result=[1,2];
    if(n==0){
      result=[]
    }else if(n==1){
      result =[1]
    }else if(n==2){
      result =[1,2]
    }
    for(let i=2; i<n; i++){
      let next= result[i-2] + result[i-1]
      result.push(next) 
    }
  let evenvalue = 0
  for(let i =0; i<= result.length; i++){
    if(result[i]%2 == 0 && result[i] <= n){
      evenvalue = evenvalue + result[i]
    }
  }
  // 1,2,3,5,8,13,21,34,55,89
    return evenvalue;
  }