using static System.Runtime.InteropServices.JavaScript.JSType;

namespace fiboEvenSum
{

    // Each new term in the Fibonacci sequence is generated by adding the previous two terms.
    // By starting with 1 and 2, the first 10 terms will be:

    // 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
    // By considering the terms in the Fibonacci sequence whose values do not exceed n, 
    //find the sum of the even-valued terms.
    //function fiboEvenSum(n)
    //{
      //  let result =[1, 2];
        
    internal class Program
    {
        static void Main(string[] args)
        {
            
            Console.WriteLine("enter a number");
            string number = Console.ReadLine();
            int n = Convert.ToInt32(number);
            int[] result = new int[n];
            result = new int[] { 1, 2 };
            if (n == 0)
            {
                result = Array.Empty<int>();
        }
            else if (n == 1)
            {
                result = new int[] { 1 };
        }
            else if (n == 2)
            {
                result = new int[] { 1, 2 };
        }
            for (int i = 2; i < n; i++)
            {
                int next = result[i - 2] + result[i - 1];
                result[i] = next;
            }
            int evenvalue = 0;
            for (int i = 0; i <= result.Length; i++)
            {
                if (result[i] % 2 == 0 && result[i] <= n)
                {
                    Console.WriteLine(result[i]);
                    evenvalue = evenvalue + result[i];
                }
            }
            // 1,2,3,5,8,13,21,34,55,89        
        Console.WriteLine(result);
        }
    }
}